--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/25/2020 3:27:52 AM
-- Server version: 8.0.19
-- Client version: 4.1
--


-- SET NAMES 'compatibility';

INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D796P77', 'AR5976', 2253);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D249P11', 'AR3549', 14533);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D293P06', 'AR6100', 12533);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D810P40', 'AR4215', 11909);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D918P95', 'AR2059', 253);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D437P23', 'AR6742', 9909);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D246P62', 'AR4310', 7567);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D064P60', 'AR3533', 14534);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D923P00', 'AR4310', 17866);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D799P96', 'AR3533', 11910);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D165P56', 'AR3533', 2254);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D822P21', 'AR8711', 254);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D896P50', 'AR3380', 19865);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D592P68', 'AR3153', 12534);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D469P96', 'AR5123', 17867);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D072P86', 'AR8898', 14535);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D199P28', 'AR9963', 12535);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D143P63', 'AR3380', 19866);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D535P31', 'AR8711', 14536);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D320P63', 'AR6100', 12536);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D265P79', 'AR8898', 14537);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D323P91', 'AR3549', 2255);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D453P79', 'AR3866', 17868);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D292P98', 'AR3153', 19867);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D910P47', 'AR3533', 5567);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D770P70', 'AR5405', 255);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D051P33', 'AR6100', 7568);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D837P89', 'AR8901', 9910);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D295P89', 'AR2059', 17869);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D397P06', 'AR6100', 12537);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D012P02', 'AR0816', 5568);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D317P88', 'AR8901', 2256);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D028P15', 'AR1738', 14538);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D413P90', 'AR9963', 12538);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D722P83', 'AR5976', 19868);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D284P68', 'AR3380', 17870);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D477P63', 'AR8925', 11911);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D150P38', 'AR8711', 19869);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D096P26', 'AR3380', 256);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D314P14', 'AR3153', 9911);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D851P99', 'AR2059', 17871);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D648P81', 'AR3866', 19870);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D578P43', 'AR6100', 17872);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D083P92', 'AR1738', 2257);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D322P89', 'AR5123', 14539);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D831P68', 'AR9261', 7569);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D125P76', 'AR5405', 11912);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D866P83', 'AR8901', 5569);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D525P26', 'AR1351', 7570);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D106P09', 'AR2492', 257);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D572P51', 'AR3380', 9912);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D812P10', 'AR3549', 12539);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D787P03', 'AR8711', 2258);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D866P61', 'AR4215', 19871);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D268P15', 'AR8925', 258);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D017P93', 'AR2059', 5570);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D212P06', 'AR1351', 7571);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D221P95', 'AR5976', 14540);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D523P55', 'AR2059', 12540);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D027P69', 'AR9261', 2259);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D637P99', 'AR5405', 259);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D603P76', 'AR2492', 2260);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D515P82', 'AR1351', 17873);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D491P64', 'AR5405', 19872);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D228P43', 'AR8901', 17874);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D798P63', 'AR9963', 5571);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D343P65', 'AR2059', 7572);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D300P12', 'AR9963', 260);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D472P66', 'AR2492', 19873);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D986P59', 'AR0816', 5572);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D747P91', 'AR8898', 2261);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D997P19', 'AR1351', 7573);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D853P94', 'AR9261', 261);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D354P01', 'AR3533', 17875);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D962P00', 'AR2492', 11913);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D743P17', 'AR8925', 19874);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D090P82', 'AR9081', 5573);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D078P92', 'AR1738', 7574);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D078P69', 'AR8925', 17876);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D440P45', 'AR4310', 19875);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D900P97', 'AR8898', 17877);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D190P95', 'AR6742', 5574);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D017P16', 'AR2059', 19876);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D677P27', 'AR1738', 17878);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D317P14', 'AR3380', 9913);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D971P79', 'AR6742', 7575);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D477P51', 'AR4215', 5575);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D600P05', 'AR5405', 2262);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D402P44', 'AR1351', 19877);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D429P52', 'AR6742', 7576);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D188P99', 'AR6100', 14541);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D947P67', 'AR0816', 5576);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D495P26', 'AR1351', 262);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D572P95', 'AR9261', 12541);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D174P66', 'AR3866', 14542);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D530P39', 'AR3533', 11914);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D172P71', 'AR3380', 17879);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D837P96', 'AR8925', 19878);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D336P18', 'AR3533', 2263);
INSERT INTO departamento_suminstro(Departamento_NroDepartamento, Suministros_CodigoSuministro, CantSum) VALUES
('D006P38', 'AR2492', 9914);