#
# TABLE STRUCTURE FOR: departamento_suminstro
#

DROP TABLE IF EXISTS `departamento_suminstro`;

CREATE TABLE `departamento_suminstro` (
  `Departamento_NroDepartamento` int(11) NOT NULL,
  `Suministros_CodigoSuministro` varchar(6) NOT NULL,
  `CantSum` int(10) unsigned NOT NULL,
  KEY `fk_Departamento_Suminstro_Departamento1_idx` (`Departamento_NroDepartamento`),
  KEY `fk_Departamento_Suminstro_Suministros1_idx` (`Suministros_CodigoSuministro`),
  CONSTRAINT `fk_Departamento_Suminstro_Departamento1` FOREIGN KEY (`Departamento_NroDepartamento`) REFERENCES `departamento` (`NroDepartamento`),
  CONSTRAINT `fk_Departamento_Suminstro_Suministros1` FOREIGN KEY (`Suministros_CodigoSuministro`) REFERENCES `suministros` (`CodigoSuministro`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (5, 'al4g57', 371);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (11, 'am3v79', 449);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (25, 'ba4r15', 421);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (31, 'bg9s56', 526);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (37, 'bx9h87', 318);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (38, 'cp7k47', 193);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (42, 'dl3x30', 57);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (44, 'eh0q74', 708);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (50, 'fz6n74', 522);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (57, 'jh3s19', 689);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (59, 'kl0x15', 363);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (60, 'ni7e19', 615);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (62, 'nq2c64', 150);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (73, 'ot2e87', 297);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (79, 'rg1a42', 137);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (87, 'sh7c07', 820);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (88, 'sk6y52', 57);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (118, 'sk7r39', 254);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (124, 'sl7t43', 562);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (125, 'sn4e68', 194);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (126, 'ss1z79', 300);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (137, 'sx8b10', 33);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (149, 'tn5l30', 964);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (152, 'tx1z28', 785);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (154, 'ty4s65', 569);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (157, 'ug9y52', 662);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (160, 'uo9z41', 806);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (171, 'wl3i67', 468);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (174, 'ww1l19', 598);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (192, 'xi6q50', 907);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (194, 'al4g57', 621);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (204, 'am3v79', 516);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (209, 'ba4r15', 930);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (210, 'bg9s56', 977);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (226, 'bx9h87', 995);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (233, 'cp7k47', 818);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (235, 'dl3x30', 587);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (244, 'eh0q74', 564);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (248, 'fz6n74', 754);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (260, 'jh3s19', 921);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (261, 'kl0x15', 192);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (271, 'ni7e19', 349);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (272, 'nq2c64', 838);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (286, 'ot2e87', 902);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (288, 'rg1a42', 927);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (290, 'sh7c07', 224);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (295, 'sk6y52', 39);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (302, 'sk7r39', 427);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (311, 'sl7t43', 31);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (315, 'sn4e68', 47);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (319, 'ss1z79', 0);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (321, 'sx8b10', 879);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (334, 'tn5l30', 454);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (342, 'tx1z28', 918);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (355, 'ty4s65', 223);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (365, 'ug9y52', 305);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (376, 'uo9z41', 353);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (378, 'wl3i67', 769);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (382, 'ww1l19', 405);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (389, 'xi6q50', 315);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (398, 'al4g57', 68);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (399, 'am3v79', 807);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (400, 'ba4r15', 517);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (407, 'bg9s56', 83);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (411, 'bx9h87', 935);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (413, 'cp7k47', 103);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (422, 'dl3x30', 470);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (423, 'eh0q74', 897);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (426, 'fz6n74', 895);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (438, 'jh3s19', 713);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (439, 'kl0x15', 157);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (440, 'ni7e19', 999);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (450, 'nq2c64', 58);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (461, 'ot2e87', 522);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (497, 'rg1a42', 639);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (505, 'sh7c07', 760);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (506, 'sk6y52', 433);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (508, 'sk7r39', 2);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (509, 'sl7t43', 874);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (527, 'sn4e68', 174);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (531, 'ss1z79', 431);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (550, 'sx8b10', 490);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (551, 'tn5l30', 856);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (555, 'tx1z28', 30);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (556, 'ty4s65', 554);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (564, 'ug9y52', 497);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (569, 'uo9z41', 717);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (571, 'wl3i67', 653);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (582, 'ww1l19', 70);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (588, 'xi6q50', 319);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (594, 'al4g57', 860);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (595, 'am3v79', 6);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (599, 'ba4r15', 379);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (608, 'bg9s56', 762);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (613, 'bx9h87', 136);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (614, 'cp7k47', 215);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (619, 'dl3x30', 864);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (630, 'eh0q74', 338);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (631, 'fz6n74', 150);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (639, 'jh3s19', 434);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (645, 'kl0x15', 365);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (654, 'ni7e19', 774);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (657, 'nq2c64', 651);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (659, 'ot2e87', 664);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (687, 'rg1a42', 413);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (693, 'sh7c07', 562);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (703, 'sk6y52', 848);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (714, 'sk7r39', 92);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (722, 'sl7t43', 615);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (727, 'sn4e68', 990);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (728, 'ss1z79', 345);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (736, 'sx8b10', 150);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (745, 'tn5l30', 458);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (762, 'tx1z28', 99);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (764, 'ty4s65', 557);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (772, 'ug9y52', 783);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (774, 'uo9z41', 910);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (777, 'wl3i67', 23);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (783, 'ww1l19', 322);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (793, 'xi6q50', 706);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (799, 'al4g57', 571);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (807, 'am3v79', 426);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (817, 'ba4r15', 493);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (825, 'bg9s56', 17);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (828, 'bx9h87', 422);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (833, 'cp7k47', 29);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (839, 'dl3x30', 876);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (840, 'eh0q74', 204);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (844, 'fz6n74', 639);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (852, 'jh3s19', 353);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (872, 'kl0x15', 655);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (873, 'ni7e19', 931);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (876, 'nq2c64', 123);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (877, 'ot2e87', 180);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (878, 'rg1a42', 542);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (882, 'sh7c07', 621);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (889, 'sk6y52', 445);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (892, 'sk7r39', 415);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (901, 'sl7t43', 640);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (907, 'sn4e68', 821);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (912, 'ss1z79', 599);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (920, 'sx8b10', 115);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (922, 'tn5l30', 799);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (934, 'tx1z28', 169);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (939, 'ty4s65', 235);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (950, 'ug9y52', 316);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (952, 'uo9z41', 560);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (953, 'wl3i67', 802);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (959, 'ww1l19', 50);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (970, 'xi6q50', 995);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (976, 'al4g57', 831);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (980, 'am3v79', 404);
INSERT INTO `departamento_suminstro` (`Departamento_NroDepartamento`, `Suministros_CodigoSuministro`, `CantSum`) VALUES (998, 'ba4r15', 66);


