#
# TABLE STRUCTURE FOR: departamento
#

DROP TABLE IF EXISTS `departamento`;

CREATE TABLE `departamento` (
  `NroDepartamento` int(11) NOT NULL,
  `EspecialidadDepto` varchar(45) NOT NULL,
  PRIMARY KEY (`NroDepartamento`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (5, 'Neumología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (11, 'Pediatría');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (25, 'Nefrología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (31, 'Oncología radioterápica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (37, 'Inmunología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (38, 'Oftalmología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (42, 'Oncología médica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (44, 'Infectología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (50, 'Cirugía cardíaca');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (57, 'Cirugía general');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (59, 'Epidemiología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (60, 'Hepatología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (62, 'Oncología médica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (73, 'Nutriología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (79, 'Infectología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (87, 'Inmunología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (88, 'Oftalmología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (118, 'Epidemiología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (124, 'Oftalmología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (125, 'Infectología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (126, 'Toxicología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (137, 'Hepatología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (149, 'Epidemiología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (152, 'Epidemiología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (154, 'Neumología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (157, 'Neurología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (160, 'Cirugía cardíaca');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (171, 'Oncología médica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (174, 'Toxicología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (192, 'Neurología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (194, 'Neurología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (204, 'Neumología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (209, 'Epidemiología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (210, 'Nutriología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (226, 'Neurocirugía');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (233, 'Psiquiatría');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (235, 'Nefrología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (244, 'Infectología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (248, 'Psiquiatría');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (260, 'Neumología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (261, 'Psiquiatría');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (271, 'Infectología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (272, 'Neurología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (286, 'Oncología médica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (288, 'Oncología médica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (290, 'Cirugía general');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (295, 'Neurología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (302, 'Oncología médica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (311, 'Toxicología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (315, 'Nutriología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (319, 'Hepatología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (321, 'Oftalmología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (334, 'Pediatría');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (342, 'Hepatología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (355, 'Toxicología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (365, 'Cirugía cardíaca');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (376, 'Cirugía cardíaca');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (378, 'Oncología radioterápica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (382, 'Neurocirugía');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (389, 'Psiquiatría');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (398, 'Pediatría');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (399, 'Oncología radioterápica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (400, 'Infectología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (407, 'Nefrología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (411, 'Neurología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (413, 'Cirugía general');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (422, 'Toxicología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (423, 'Inmunología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (426, 'Neurocirugía');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (438, 'Psiquiatría');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (439, 'Cirugía general');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (440, 'Neurocirugía');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (450, 'Toxicología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (461, 'Pediatría');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (497, 'Toxicología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (505, 'Inmunología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (506, 'Toxicología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (508, 'Nutriología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (509, 'Cirugía cardíaca');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (527, 'Oncología radioterápica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (531, 'Hepatología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (550, 'Toxicología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (551, 'Oftalmología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (555, 'Nefrología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (556, 'Oncología radioterápica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (564, 'Neumología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (569, 'Toxicología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (571, 'Toxicología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (582, 'Oncología radioterápica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (588, 'Neumología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (594, 'Cirugía general');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (595, 'Nefrología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (599, 'Oncología radioterápica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (608, 'Nutriología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (613, 'Inmunología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (614, 'Oftalmología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (619, 'Cirugía cardíaca');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (630, 'Hepatología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (631, 'Psiquiatría');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (639, 'Hepatología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (645, 'Oncología médica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (654, 'Inmunología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (657, 'Epidemiología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (659, 'Oncología radioterápica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (687, 'Cirugía cardíaca');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (693, 'Oncología médica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (703, 'Infectología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (714, 'Oncología radioterápica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (722, 'Oncología radioterápica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (727, 'Oncología radioterápica');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (728, 'Psiquiatría');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (736, 'Toxicología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (745, 'Nefrología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (762, 'Nutriología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (764, 'Cirugía cardíaca');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (772, 'Epidemiología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (774, 'Neumología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (777, 'Oftalmología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (783, 'Cirugía cardíaca');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (793, 'Neurocirugía');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (799, 'Pediatría');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (807, 'Epidemiología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (817, 'Nutriología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (825, 'Hepatología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (828, 'Neurología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (833, 'Cirugía cardíaca');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (839, 'Nutriología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (840, 'Nutriología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (844, 'Inmunología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (852, 'Cirugía general');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (872, 'Hepatología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (873, 'Psiquiatría');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (876, 'Oftalmología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (877, 'Oftalmología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (878, 'Oftalmología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (882, 'Epidemiología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (889, 'Nefrología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (892, 'Nefrología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (901, 'Neumología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (907, 'Nefrología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (912, 'Psiquiatría');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (920, 'Nefrología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (922, 'Hepatología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (934, 'Infectología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (939, 'Epidemiología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (950, 'Cirugía general');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (952, 'Nefrología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (953, 'Inmunología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (959, 'Nefrología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (970, 'Neumología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (976, 'Nefrología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (980, 'Neumología');
INSERT INTO `departamento` (`NroDepartamento`, `EspecialidadDepto`) VALUES (998, 'Oncología radioterápica');


