#
# TABLE STRUCTURE FOR: pacientedomicilio
#

DROP TABLE IF EXISTS `pacientedomicilio`;

CREATE TABLE `pacientedomicilio` (
  `Domicilio_Personas_DNI` int(10) unsigned NOT NULL,
  `Direccion` varchar(65) NOT NULL,
  `Tipo` varchar(45) NOT NULL,
  PRIMARY KEY (`Domicilio_Personas_DNI`),
  KEY `fk_PacienteDomicilio_Pacientes1_idx` (`Domicilio_Personas_DNI`),
  CONSTRAINT `fk_PacienteDomicilio_Pacientes1` FOREIGN KEY (`Domicilio_Personas_DNI`) REFERENCES `pacientes` (`Personas_DNI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35004174, '068 Beier Common Suite 026', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35051811, '977 Cormier Roads', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35084332, '3437 Graham Valleys Apt. 282', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35107827, '0248 Quitzon Turnpike Apt. 374', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35132371, '5974 Zoie Cliffs Apt. 422', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35141864, '72634 Athena Rapids', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35153908, '9900 Arjun Viaduct', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35154951, '585 Jovanny Camp Apt. 052', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35175099, '374 Jakob Mountain', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35178186, '599 Talon Mall', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35202766, '975 Hermann Road', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35295915, '2673 Patience Alley', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35316215, '9413 Lemuel Parks', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35350776, '1705 Waelchi Gateway', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35352845, '854 Jeanette Isle', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35359996, '570 Else Ferry', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35370386, '19838 Lockman Station Suite 933', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35406867, '7088 Ernie Mountain Apt. 180', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35419854, '8091 Beahan Court Suite 049', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35433629, '76531 Gianni Cape Suite 405', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35446516, '08274 Trantow Street Suite 089', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35476885, '71642 Emilia Vista Apt. 450', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35477869, '252 Kerluke Cliffs Apt. 442', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35479415, '160 Danial Crest', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35505339, '75999 Kilback Crossing', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35514292, '4082 Jace Road', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35523736, '263 Johns Lane Suite 351', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35537163, '93742 Tre Ways Apt. 018', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35546365, '34940 Breitenberg Neck Suite 978', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35547038, '87520 Letitia Dale Apt. 833', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35572091, '825 Sipes Parks Suite 361', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35606308, '6848 Purdy Light Suite 246', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35621680, '9706 Hudson Vista', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35672651, '1010 Hermann Track Suite 093', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35694744, '4540 Ebba Mission Suite 411', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35703957, '45590 Natalia Orchard', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35784576, '6583 Kertzmann Valleys', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35785180, '4299 Metz Trail', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35791930, '05600 Thompson Drive Apt. 384', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35799311, '7626 Meta Ville Apt. 603', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35812770, '26325 Beer Ford Suite 685', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35833927, '9408 Ines Points Apt. 885', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35837353, '071 Jennie Mountains', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35844724, '57321 Jennifer Lock Apt. 616', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35845869, '7882 Audreanne Harbor Apt. 561', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35846788, '92860 Reilly Squares', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35851858, '4344 Merle Garden', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35880343, '845 Greenfelder Cliffs', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35899113, '69394 Abbigail Isle', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35899824, '6494 Colt Street', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35906761, '79405 Gleichner Fork', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35920416, '387 Zetta Extensions', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35926930, '0513 Tremblay Isle', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35961410, '217 Barrows Rapids Suite 429', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35983236, '6825 Ford Meadows', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35986619, '16992 Camryn Garden Apt. 589', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (35997187, '62641 Baumbach Plains Suite 768', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36006003, '01277 Auer Mission', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36048364, '648 Isai Tunnel Apt. 702', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36055074, '231 McDermott Spring', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36064744, '308 Marian Inlet Suite 966', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36081338, '685 Blanda Station Suite 731', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36082125, '43389 Paucek Junction Apt. 245', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36101236, '3702 Bergnaum Passage', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36116116, '1956 Schumm Drive', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36156580, '77296 Legros Shoals Suite 709', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36161168, '00923 Jerde Common Apt. 681', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36200630, '8202 Morton Hills', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36220328, '693 Lavada Spring Apt. 507', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36265351, '627 Price Pike', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36325506, '5953 Littel Island Suite 258', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36329106, '3278 Dejah Creek', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36378283, '8521 Bayer Isle Suite 753', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36388290, '595 Gayle Underpass', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36388522, '514 Ruby Spur', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36401744, '15734 Lockman Fall Apt. 014', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36456127, '672 Robbie Crossing', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36493248, '20858 Nitzsche Court', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36496837, '613 Flavio Land Apt. 865', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36550174, '986 Howell Plaza Apt. 233', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36584917, '6640 Vicky Brooks', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36599156, '1362 Bruen Street', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36617103, '40822 Alvera Pines Suite 641', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36645955, '202 Trudie Shoal Apt. 061', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36656580, '32667 Nitzsche Port', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36658204, '15603 Stracke Centers Suite 562', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36658866, '3293 Koch Junctions', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36664085, '915 Trantow Common', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36667179, '7996 Metz Plaza', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36686235, '082 Frami Rapids Apt. 770', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36704526, '78643 Marcelo Canyon Apt. 585', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36710006, '8393 Kautzer Summit', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36726893, '9859 Lebsack Rapid Suite 642', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36799007, '09978 Morris Course', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36810534, '96224 Barrows Mission', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36822407, '8242 Tamara Heights', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36830043, '7048 Esta Throughway', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36833083, '0495 Stark Island Suite 397', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36841870, '921 Devante Brooks Suite 627', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36898389, '17986 Heller Ports', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36913979, '62368 Bernhard Knoll', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36927884, '16602 Torp Greens Suite 603', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36952768, '55985 Halvorson Burg', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (36976377, '9790 Tad Greens', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37005264, '0210 Elliott Grove', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37065291, '91040 Florencio Course', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37081098, '834 Lang Avenue Suite 650', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37108102, '77588 Grant Common', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37129972, '0888 Crona Drive Apt. 793', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37130532, '288 Berta Village', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37135783, '004 Darlene Forges', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37156173, '453 Adams Forest Suite 509', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37157554, '34371 Fritsch Loaf', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37165091, '8573 Ansley Crescent', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37177897, '85083 Mona Branch Suite 786', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37239957, '42091 Grimes Spur', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37330968, '5916 Yessenia Tunnel', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37337857, '4704 Alex Island Apt. 857', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37338572, '630 Gail Springs Suite 354', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37372994, '9670 Kari Meadows Apt. 267', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37373800, '550 Dooley Ford Suite 870', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37388560, '820 Garland Trail Apt. 085', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37392851, '867 Torrey Dale', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37398144, '934 Carli Stream Apt. 754', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37403986, '3816 Spinka Fall', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37430627, '2097 Volkman Islands Suite 858', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37433854, '29982 Bo Fields Apt. 683', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37442358, '41403 Eichmann Meadow Apt. 021', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37468874, '6501 Amir Crest Apt. 704', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37497122, '56192 Dortha Skyway', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37588014, '5904 Wolf Wells Suite 107', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37590277, '35597 O\'Keefe Route Suite 839', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37716826, '58508 Rocio Stravenue', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37729453, '5310 Gustave Vista', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37754100, '443 Schuster Street Apt. 707', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37764692, '31267 Icie Springs', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37802120, '088 Scarlett Trail', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37810057, '39743 Cordell Inlet Suite 781', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37813663, '99558 Hintz Via Apt. 125', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37819429, '92920 Demetris Bypass Suite 695', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37824906, '318 Hilpert Spring', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37831528, '4118 Bergnaum Ridge Suite 262', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37841948, '973 Savion Inlet Suite 852', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37852517, '986 Maggie Lights Suite 899', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37871975, '108 Laila Village Suite 999', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37882972, '365 Greta Ferry Suite 696', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37892324, '62347 Halie Station', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37921533, '80251 Benedict Hills', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37925227, '1813 Kory Knoll Suite 835', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37952427, '68946 Swaniawski Trafficway Apt. 350', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37968762, '00316 Quigley Island', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37969141, '84260 Belle Village Suite 376', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37973038, '97702 Cummings Vista', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (37983125, '074 Jordi Mountains', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38009826, '62364 Mona River Apt. 795', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38010369, '15875 Carolanne Locks', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38012545, '069 Christiansen Track Apt. 872', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38019904, '4545 Helen Plain', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38022259, '85027 Doyle Glen Suite 795', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38037563, '7485 Kraig Lakes Suite 525', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38074050, '02161 Alva Row', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38074409, '919 Stefanie Meadows Apt. 898', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38108886, '498 Wolf Curve', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38113492, '91925 Dario Corner Apt. 082', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38114108, '1329 Satterfield Rapid', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38131631, '66321 Nolan Drives', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38186957, '4528 Monahan Lodge Suite 159', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38204420, '992 Ulices Fords Suite 332', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38208447, '00682 Lind Track', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38215372, '3978 Vern Rapids', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38239542, '7059 Streich Wells', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38258119, '9453 Weimann Tunnel', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38268269, '830 Hermann Brook', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38281442, '5017 Cole Station', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38299873, '94631 Gladyce Manor', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38324063, '68268 Iliana Mills', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38331609, '6606 McGlynn Forest', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38346244, '1020 Elbert Cape Apt. 307', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38369276, '7677 Amina Meadows Suite 798', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38373141, '6620 Wiza Expressway Suite 639', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38428592, '2789 Wyman Square', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38438427, '8273 Wolf Fork', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38452638, '03005 Alysha Plains', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38511985, '536 Brice Mount Suite 806', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38528811, '9430 Tyler Garden Apt. 616', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38544356, '19625 Edythe Cliffs Apt. 824', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38547790, '987 Matilde Loaf Apt. 971', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38557120, '66139 Auer Drive', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38576236, '6484 Jason Walks', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38592257, '410 Arielle Hills', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38598739, '3549 Mark Common', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38610281, '253 Bergstrom Oval', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38612701, '26396 Jakob Tunnel Suite 788', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38615048, '6275 Stanton Common Apt. 936', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38620429, '5738 Weimann Extension Apt. 455', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38641744, '041 Greenholt Lane', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38680288, '5601 Erdman Ways', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38723353, '92192 Ankunding Loaf Suite 492', 'Departamento');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38727058, '85251 Tad Vista', 'Casa');
INSERT INTO `pacientedomicilio` (`Domicilio_Personas_DNI`, `Direccion`, `Tipo`) VALUES (38731607, '53252 Kautzer Land', 'Departamento');


